site_name: krpy
theme:
  name: material
  palette:
    scheme: preference
    primary: blue grey
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Tutorial:
    - Intro: examples/1-krow/01-krow_corey.ipynb
  - Releases Notes: releases_notes.md

repo_url: https://github.com/scuervo91/krpy
repo_name: scuervo91/krpy

plugins:
  - search
  - mkdocs-jupyter

markdown_extensions:
  - admonition
